version: '3'
services:
    # PHP Service
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./app:/var/www/html
        networks:
            - laravel

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - php

    # MySQL Service
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: db1234
            MYSQL_ROOT_PASSWORD: db1234
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
